name: make_all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  containerised_build:
    runs-on: ["ubuntu-20.04"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: make all
        run: make all
